# Generated by Django 4.0.6 on 2022-07-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('procedure', models.CharField(choices=[('E', 'Extermination'), ('F', 'Feeding'), ('R', 'Reproduction')], default='E', max_length=1)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bug')),
            ],
        ),
    ]
