# Generated by Django 4.0.6 on 2022-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bug',
            name='agents',
            field=models.ManyToManyField(to='main_app.agent'),
        ),
    ]
